export const GET_VIDEO_DEFAULT_REQUEST = 'GET_VIDEO_DEFAULT_REQUEST';
export const GET_VIDEO_DEFAULT_SUCCESS = 'GET_VIDEO_DEFAULT_SUCCESS';
export const GET_VIDEO_DEFAULT_FAILURE = 'GET_VIDEO_DEFAULT_FAILURE';


export const GET_VIDEO_SEARCH_REQUEST = 'GET_VIDEO_SEARCH_REQUEST';
export const GET_VIDEO_SEARCH_SUCCESS = 'GET_VIDEO_SEARCH_SUCCESS';
export const GET_VIDEO_SEARCH_FAILURE = 'GET_VIDEO_SEARCH_FAILURE';


export const GET_VIDEO_WATCHING_REQUEST = 'GET_VIDEO_WATCHING_REQUEST';
export const GET_VIDEO_WATCHING_SUCCESS = 'GET_VIDEO_WATCHING_SUCCESS';
export const GET_VIDEO_WATCHING_FAILURE = 'GET_VIDEO_WATCHING_FAILURE';

export const GET_VIDEO_RELATED_REQUEST = 'GET_VIDEO_RELATED_REQUEST';
export const GET_VIDEO_RELATED_SUCCESS = 'GET_VIDEO_RELATED_SUCCESS';
export const GET_VIDEO_RELATED_FAILURE = 'GET_VIDEO_RELATED_FAILURE';

export const GET_MYCHANNEL_REQUEST = "GET_MYCHANNEL_REQUEST";
export const GET_MYCHANNEL_SUCCESS = "GET_MYCHANNEL_SUCCESS";
export const GET_MYCHANNEL_FAILURE = "GET_MYCHANNEL_FAILURE";
